server:
  port: 9030
  servlet.context-path: /intelligence

spring:
  datasource:
    url: jdbc:postgresql://localhost:9010/coding-genie-intelligence-db
    username: user
    password: password
    driver-class-name: org.postgresql.Driver

  ai:
    model.chat: openai
    openai:
      api-key: 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
      base-url: https://openrouter.ai/api/v1
      chat:
        options:
          model: google/gemini-2.5-flash:free
          temperature: 0.0
      embedding:
        options:
          model: qwen/qwen3-embedding-8b

---

spring:
  config:
    activate:
      on-profile: k8s
  datasource:
    url: jdbc:postgresql://pgvector.coding-genie.svc.cluster.local:5432/intelligence_db
    username: intelligence_user
    password: ${DB_PASSWORD}

  ai:
    openai:
      api-key: ${AI_API_KEY}
    chat:
        options:
          model: google/gemini-2.5-flash:free
